In [27]:
#Why is NumPy Faster Than Lists?
#NumPy arrays are stored at one continuous place in memory unlike lists, 
#so processes can access and manipulate them very efficiently.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [4]:
# 2D arrays
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [29]:
# array indexing
arr = np.array((1, 2, 3, 4, 5))
print(arr[3])

4


In [7]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


In [30]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10], [4,3,5,6,7]])

print('Last element from 2nd dim: ', arr[-1, -4])

Last element from 2nd dim:  3


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [10]:
print(arr[4:])

[5 6 7]


In [11]:
print(arr[:4])

[1 2 3 4]


In [12]:
print(arr[-3:-1])

[5 6]


In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])



[2 4]


In [14]:
print(arr[::2])

[1 3 5 7]


In [33]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [16]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9,10]])

print(arr[0:2, 2])

[3 8]


In [17]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [18]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [19]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [20]:
#iterating thru rows
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [21]:
#thru each dimesnsion
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [22]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [23]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [24]:
#using stack function

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [25]:
#along row
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [26]:
#along cols
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
#splitting arraysimport numpy as np


import numpy as np

arr = np.array([1, 2, 3, 4, 5,6])

newarr = np.array_split(arr, 3) #no.of splits

print(newarr)

[array([1, 2]), array([3, 4]), array([5])]


In [4]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [5]:
#Searching Arrays
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

#return index values
print(x)

(array([3, 5, 6], dtype=int64),)


In [6]:
#find index having odd & even values

In [7]:
#Sorting Arrays
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [8]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [9]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
